# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configure and boot strap Debian 12 for Kubernetes lab environment
Vagrant.configure("2") do |config|
  # Vagrant box image
  config.vm.box = "generic/debian12"

  # Allocated resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  # Sync'd folders
  config.vm.synced_folder ".", "/home/vagrant/sync"

  # Portforwarding
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Bootstrap VM
  config.vm.provision "shell", inline: <<-SHELL
    # Update Debian
    sudo apt-get update && sudo apt-get upgrade

    # Install Docker Engine
    apt-get install ca-certificates gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    usermod -aG docker vagrant

    # Install Kubernetes
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    chmod +x ./kind
    mv ./kind /usr/local/bin/kind
    curl -LO https://dl.k8s.io/release/v1.26.10/bin/linux/amd64/kubectl
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm -f /home/vagrant/kubectl

    # Install Helm
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt-get update
    apt-get install helm

    # Configuration
    git config --global user.name "Patrick B"
    it config --global user.email "patrick777@tuta.io"

    # To Do
    # Copy SSH keys to ~/.ssh
  SHELL
end
